In [1]:
import numpy as np
import cv2
import os
import tensorflow as tf


In [2]:
train = 'walk_or_run_train/train'
test = 'walk_or_run_test/test'
categories = ['walk','run']
img_size=50

In [3]:
training_data=[]
test_data=[]

In [4]:
#importing train data
def create_training_data():
    for category in categories:
        path=os.path.join(train, category)
        class_num=categories.index(category)
        for img in os.listdir(path):
            try:
                img_array = cv2.imread(os.path.join(path,img), cv2.IMREAD_GRAYSCALE)
                new_array=cv2.resize(img_array, (img_size, img_size))
                training_data.append([new_array,class_num])
            except Exception as e:
                pass

create_training_data()

In [5]:
len(training_data)

600

In [10]:
#importing test_data
def create_test_data():
    for category in categories:
        path=os.path.join(test, category)
        class_num=categories.index(category)
        for img in os.listdir(path):
            try:
                img_array = cv2.imread(os.path.join(path,img), cv2.IMREAD_GRAYSCALE)
                new_array=cv2.resize(img_array, (img_size,img_size))
                test_data.append([new_array,class_num])
            except Exception as e:
                pass

create_test_data()

In [11]:
len(test_data)

141

In [12]:
# shuffling data to make sure that your training/test/validation sets are representative of the overall distribution of the data.
import random
random.shuffle(training_data)
random.shuffle(test_data)

In [198]:
#
X_train = []
y_train = []

In [199]:
#you need to flatten the input data so that you would  be able to run it through the tf.session
for features,label in training_data:
    X_train.append(features.flatten())
    y_train.append(label)

In [212]:
X_train=np.array(X_train)#.reshape(-1, IMG_SIZE,IMG_SIZE,1)
y_train=np.array(y_train)

In [213]:
X_train[2]

array([156, 153, 160, ..., 113, 103,  81], dtype=uint8)

In [214]:
X_test = []
y_test = []

In [215]:
for features, label in test_data:
    X_test.append(features.flatten())
    y_test.append(label)

In [216]:
X_test = np.array(X_test)
y_test = np.array(y_test)

In [217]:
print(len(X_test))

141


In [218]:
X_train

array([[ 28,  24,  24, ...,  19,  14,  35],
       [255, 255, 255, ..., 255, 255, 255],
       [156, 153, 160, ..., 113, 103,  81],
       ...,
       [140, 138, 108, ..., 122, 141, 104],
       [ 88, 105,  99, ..., 188, 192, 187],
       [158, 217, 243, ..., 163, 156, 138]], dtype=uint8)

In [219]:
y_train

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,

In [220]:
#you  need to create a one hotcode tensor for the class attribute as we saw in the mnist dataset i.e.(one_hot=True)
#using one hot encoder to transform the data 
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = y_train.reshape(len(y_train), 1)
y_train = onehot_encoder.fit_transform(integer_encoded)
#y_train = np.eye(2)[np.array(y_train).reshape(-1)]


C:\Users\oa87046\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [221]:
#you  need to create a one hotcode tensor for the class attribute for the test dataset
y_test = np.eye(2)[np.array(y_test).reshape(-1)]

In [222]:

y_train

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [223]:
#parameters
learning_rate = 0.001
training_epochs = 50
batch_size = 100

In [224]:
# Network Parameters
n_hidden_1 = 128 # 1st layer number of features
n_hidden_2 =64# 2nd layer number of features
n_input = 2500 # (img shape: 50*50)
n_classes = 2 # walk or run
n_samples = len(training_data)

In [177]:
#X_train=tf.keras.utils.normalize(X_train, axis=1)
#x_test = tf.keras.utils.normalize(X_test, axis=1)

In [178]:
x = tf.placeholder("float", [None, n_input])
y = tf.placeholder("float", [None, n_classes])

In [179]:
def multilayer_perceptron(x, weights, biases):
    '''
    x : Place Holder for Data Input
    weights: Dictionary of weights
    biases: Dicitionary of biases
    '''
    
    # First Hidden layer with RELU activation
    layer_1 = tf.add(tf.matmul(x, weights['h1']), biases['b1'])
    layer_1 = tf.nn.relu(layer_1)
    
    # Second Hidden layer with RELU activation
    layer_2 = tf.add(tf.matmul(layer_1, weights['h2']), biases['b2'])
    layer_2 = tf.nn.relu(layer_2)
    
    # Last Output layer with linear activation
    out_layer = tf.matmul(layer_2, weights['out']) + biases['out']
    return out_layer

In [180]:
weights = {
    'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))
}

In [181]:
biases = {
    'b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'b2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}

In [182]:
# Construct model
pred = multilayer_perceptron(x, weights, biases)

In [183]:
# Define loss and optimizer
cost=tf.nn.sigmoid_cross_entropy_with_logits(logits = pred, labels= y)
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

In [184]:
# Initializing the variables
init = tf.initialize_all_variables()

In [194]:
# Launch the session
sess = tf.InteractiveSession()

# Intialize all the variables
sess.run(init)

# Training Epochs
# Essentially the max amount of loops possible before we stop
# May stop earlier if cost/loss limit was set
for epoch in range(training_epochs):

    # Start with cost = 0.0
    avg_cost = 0.0

    # Convert total number of batches to integer
    total_batch = int(n_samples/batch_size)

    # Loop over all batches
    for i in range(total_batch):
        # Grab the next batch of training data and labels
        #begin at 0:100-->100:200-->200:300-->300-->400
        begin=batch_size*i
        end=begin+batch_size
        batch_x = X_train[begin:end]
        batch_y = y_train[begin:end]
        _, c = sess.run([optimizer, cost], feed_dict={x: batch_x, y: batch_y})
        # Compute average loss
        avg_cost += c / total_batch

    print("Epoch: {} cost={}".format(epoch+1,avg_cost[-1]))

print("Model has completed {} Epochs of Training".format(training_epochs))
       

Epoch: 1 cost=[136609.95 110692.59]
Epoch: 2 cost=[ 88724.86 134286.36]
Epoch: 3 cost=[38203.684 21598.615]
Epoch: 4 cost=[38721.81  89731.664]
Epoch: 5 cost=[18308.688 34208.7  ]
Epoch: 6 cost=[12642.37  66027.195]
Epoch: 7 cost=[ 7325.7554 27107.969 ]
Epoch: 8 cost=[ 1319.2997 53867.543 ]
Epoch: 9 cost=[ 7535.401 46038.355]
Epoch: 10 cost=[13246.836 26859.01 ]
Epoch: 11 cost=[12325.4795 25906.541 ]
Epoch: 12 cost=[11653.986 18616.25 ]
Epoch: 13 cost=[ 7563.719  12762.1455]
Epoch: 14 cost=[6913.6875 7330.9375]
Epoch: 15 cost=[6168.1304 4210.677 ]
Epoch: 16 cost=[14326.117     507.29202]
Epoch: 17 cost=[10361.064  9765.72 ]
Epoch: 18 cost=[6896.4106 1608.7295]
Epoch: 19 cost=[5011.794    462.88516]
Epoch: 20 cost=[2453.428    0.   ]
Epoch: 21 cost=[13420.609  3459.344]
Epoch: 22 cost=[19878.912     0.   ]
Epoch: 23 cost=[24873.4       971.61475]
Epoch: 24 cost=[23947.51     0.  ]
Epoch: 25 cost=[11338.553     0.   ]
Epoch: 26 cost=[5481.217  3701.8542]
Epoch: 27 cost=[9845.276 3294.177

In [186]:
# Test model
correct_predictions = tf.equal(tf.argmax(pred, 1), tf.argmax(y, 1))

In [187]:
print(correct_predictions[0])

Tensor("strided_slice_1:0", shape=(), dtype=bool)


In [188]:
correct_predictions = tf.cast(correct_predictions, "float")

In [189]:
accuracy = tf.reduce_mean(correct_predictions)

In [190]:
print("Accuracy:", accuracy.eval({x: X_test, y: y_test}))

Accuracy: 0.5460993


In [ ]:
#normalizing the data  will reduce the cost value 