### Bag of words
   
1. Representation of text that describes the occuerence of words within a text 
2. Any information about order or structure is discarded
3. Represent document x as set of(wi,fi)

We convert text to a numerical represenattion called a feature vector . A feature vector can be as simple as a list of numbers.


In [1]:
measurements=[{'city':'Dubai','temperature':33.},
              {'city':'London','temperature':12.},
              {'city':'San Francsisco','temperature':18.},{'city':'Toronto','temperature':14.},]
#Transforms list of feature-value 
from sklearn.feature_extraction import DictVectorizer
vec=DictVectorizer()

In [2]:
print(vec.fit_transform(measurements).toarray())

[[ 1.  0.  0.  0. 33.]
 [ 0.  1.  0.  0. 12.]
 [ 0.  0.  1.  0. 18.]
 [ 0.  0.  0.  1. 14.]]


In [3]:
print(vec.get_feature_names())

['city=Dubai', 'city=London', 'city=San Francsisco', 'city=Toronto', 'temperature']


###  Methods in DictVectorizer
1. fit(X[,y])	Learn a list of feature name -> indices mappings.
2. fit_transform(X[,y])	Learn a list of feature name -> indices mappings and transform X.
3. get_feature_names()	Returns a list of feature names, ordered by their indices.
4. get_params([deep])	Get parameters for this estimator.
5. inverse_transform(X[, dict_type])	Transform array or sparse matrix X back to feature mappings.
6. restrict(support[, indices])	Restrict the features to those in support using feature selection.
7. set_params(**params)	Set the parameters of this estimator.
8. transform(X)	Transform feature->value dicts to array or sparse matrix.

In [4]:
#convert a collection of text documents to a matrix of token counts
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
corpus=[
    'Mcmaster BDA 102 is an interesting course',
    'I can not wait for Saturday!',
    'Mcmaster students shall use BDA 102 to successfully combat Skynet',
    'I wish i was as strong as thanos',
    'Sarah Conor is out of reach.'
]
#print(type(corpus))
#print(len(corpus))

In [6]:
print(corpus)

['Mcmaster BDA 102 is an interesting course', 'I can not wait for Saturday!', 'Mcmaster students shall use BDA 102 to successfully combat Skynet', 'I wish i was as strong as thanos', 'Sarah Conor is out of reach.']


In [44]:
vectorizer=CountVectorizer(ngram_range=(3, 1))

In [45]:
print(vectorizer)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(3, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)


In [46]:
print(vectorizer.fit_transform(corpus).todense())
#todense converts to a spare matrix

[[1 1 0 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 1 0 1 1 0 0 0]
 [0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]]


In [47]:
print(vectorizer.vocabulary_)

{'mcmaster': 11, 'bda': 3, '102': 0, 'is': 10, 'an': 1, 'interesting': 9, 'course': 7, 'can': 4, 'not': 12, 'wait': 26, 'for': 8, 'saturday': 17, 'students': 21, 'shall': 18, 'use': 25, 'to': 24, 'successfully': 22, 'combat': 5, 'skynet': 19, 'wish': 28, 'was': 27, 'as': 2, 'strong': 20, 'thanos': 23, 'sarah': 16, 'conor': 6, 'out': 14, 'of': 13, 'reach': 15}


###  Methods in CountVectorizer
1. build_analyzer()	Return a callable that handles preprocessing and tokenization
2. build_preprocessor()	Return a function to preprocess the text before tokenization
3. build_tokenizer()	Return a function that splits a string into a sequence of tokens
4. decode(doc)	Decode the input into a string of unicode symbols
5. fit(raw_documents[, y])	Learn a vocabulary dictionary of all tokens in the raw documents.
6. fit_transform(raw_documents[, y])	Learn the vocabulary dictionary and return term-document matrix.
7. get_feature_names()	Array mapping from feature integer indices to feature name
8. get_params([deep])	Get parameters for this estimator.
9. get_stop_words()	Build or fetch the effective stop words list
10. inverse_transform(X)	Return terms per document with nonzero entries in X.
11. set_params(**params)	Set the parameters of this estimator.
12. transform(raw_documents)	Transform documents to document-term matrix.

In [18]:
#Application
train_set=("The sky is blue,", "The sun is bright.")
test_set=(" The sun in the sky is bright.",
          "We can see the shining sun ,the bright sun.")

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer =CountVectorizer(stop_words='english',encoding='utf-16')
vectorizer.fit_transform(train_set)
print(vectorizer.vocabulary_)

{'sky': 2, 'blue': 0, 'sun': 3, 'bright': 1}


In [33]:
print(vectorizer.transform(test_set))

  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (1, 1)	1
  (1, 3)	2


In [35]:
print(vectorizer.transform(test_set).todense())

[[0 1 1 1]
 [0 1 0 2]]


## CLASS ACTIVITY
1. go to this avenue select the welcome message from BDA 102 and 101 or BDA 104 OR BDA 103

2. create a list with  variables containing each text message 

3. Build vocubalary then print array from the list


## Quiz 2

1. Sum the two rows and build a frequency table

2. check type and see whether it is dataframe 

3. if not dataframe,convert it to a dataframe.

4. To this dataframe give a column name 